# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "ipaclient.example.com"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.11"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
      # Create a fallback sudo user with a password
      useradd -m usersudo
      usermod -aG wheel usersudo
      echo '%wheel	ALL=(ALL:ALL) ALL' >> /etc/sudoers
      echo 'usersudo' | passwd --stdin usersudo
      cp /etc/ssh/sshd_config /etc/ssh/sshd_config.orig
      sed 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config.orig > /etc/ssh/sshd_config

      cat > /etc/hosts <<EOF
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.33.10 ipaserver.example.com ipaserver
192.168.33.11 ipaclient.example.com ipaclient
EOF

      yum update -y
      yum install -y sssd autofs
      systemctl enable autofs sssd-autofs
      systemctl start autofs

      # Config auth
      yum install -y openldap-clients nss-pam-ldapd sssd
      authconfig --enableforcelegacy --update
      authconfig --enableldap --enableldapauth --ldapserver="ipaserver.example.com" --ldapbasedn="dc=example,dc=com" --update
      authconfig --update --enablemkhomedir
      authconfig --test
  SHELL
end
