# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "ipaserver.example.com"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM.
    # IMPORTANT: this is the minimum memory suitable for the IPA server
    # to run correcly
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
      cat > /etc/hosts <<EOF
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.33.10 ipaserver.example.com ipaserver
EOF

      yum update -y
      yum install -y ipa-server bind bind-dyndb-ldap ipa-server-dns
  SHELL
end
